inc:
  # Blog Information
  title:        "Jekyll Incorporated"
  subtitle:     "Modern Jekyll based blog for companies"
  cover_image:  blog-cover.jpg
  logo:         logo.png
  
  # Company information
  company:      Incorporated
  url:          http://sendtoinc.com/
  facebook:     sendtoinc
  twitter:      sendtoinc
  gplus:        '101183822199340201470'
  about_link:   https://sendtoinc.com/about/
  
  # Product Information
  product_link: http://incorporated.sendtoinc.com/
  tagline:      "Get a modern blog for your company"
  
  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
  
  # Analytics     
  analytics:    false

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

url: http://incorporated.sendtoinc.com

# Show future posts
future:      false
show_drafts: nil

relative_permalinks: true

permalink: /:title/
paginate_path: 'page:num'
paginate: 10

# Build settings
markdown: kramdown

# sass support
sass:
    sass_dir: _sass
    style: :compressed